# Name of your application. Used to uniquely configure containers.
service: names

# Name of the container image.
image: exegeteio/names

# Deploy to these servers.
servers:
  web:
    hosts:
      - mrsk
    labels:
      traefik.http.routers.names-web.rule: Host(`names.mrsk.exegete.io`)

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com
  username:
    - MRSK_REGISTRY_PASSWORD

  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  args:
    RUBY_VERSION: 3.2.2
  remote:
    arch: amd64
    host: ssh://root@mrsk

# Configure custom arguments for Traefik
traefik:
  args:
    accesslog: true
    accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /
  port: 3000
